version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - coffee_shop_volume:/usr/share/app
    ports:
      - '5432:5432'
volumes:
  coffee_shop_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/ubuntu/csv_data
networks:
  default:
    external:
        name: blue_ocean