version: "3.7"
services:
  backend:
    image: neildudani/blue-ocean-backend
    env_file:
      - /home/ubuntu/awss3.env
    ports:
      - '80:3000'
networks:
  default:
    external:
      name: blue_ocean